name : Continuous Deployment
on: 
    workflow_run:
        workflows: ["Build and Push Docker Image"]
        types:
            - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull joshuamumo/caimax_client:latest
      - name: Delete Old Docker Container
        run: sudo docker rm -f caimax_client || true
      - name: Create .env file from secrets
        run: |
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env
          echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
          echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Run Docker Container
        run: sudo docker run --env-file .env -d --name caimax_client -p 8080:3000 -p 5555:5555 joshuamumo/caimax_client:latest
        